### ISSUE TITLE
Vocab subscripting

### ISSUE THREAD

**Issue by IdiosApps** [IdiosApps/Graded-Reader-Builder#7]
Could give page number (faster to find, but have to search through new vocab on that page to find the match), or vocab's index number (slower to find on page, but slightly easier to search through the new vocab on that page)

Would be a good option to choose between. Page number sounds better, and it seems like we will be dealing with page number calculations later anyway.

**Comment by Dyse** [comment]
Possible combination of the two, such as "pp 9.2" pointing to the second item on the 9th page's vocab.
